# Generated by Django 5.2.6 on 2026-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to=''),
        ),
    ]
