# Generated by Django 5.2.6 on 2026-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, default='defaults/no-image.png', null=True, upload_to='advertisements/'),
        ),
    ]
