# Generated by Django 5.2.6 on 2026-03-10 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_method', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('link', 'Direct Link'), ('other', 'Other')], default='link', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='myapp.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('user', 'advertisement', 'share_method')},
            },
        ),
    ]
